---
# tasks file for role_haproxy

- name: Check Packages
  ansible.builtin.package_facts:
    manager: auto

- name: Install HAProxy Package from Repository
  vars:
    supported_os: ["RedHat", "Debian"]
  ansible.builtin.include_tasks: "install-{{ ansible_os_family }}.yml"
  when: ansible_os_family in supported_os

- name: Install rsyslog
  ansible.builtin.package:
    name: rsyslog
    state: present

- name: Remove rsyslog privilege dropping for container compatibility
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: '{{ item }}'
    state: absent
  loop:
    - '^\$PrivDropToUser'
    - '^\$PrivDropToGroup'
  notify:
    - restart rsyslog

- name: Enable rsyslog UDP module for HAProxy
  ansible.builtin.template:
    src: rsyslog-udp.conf.j2
    dest: /etc/rsyslog.d/00-udp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rsyslog

- name: configure haproxy logging
  ansible.builtin.template:
    src: haproxy.conf.j2
    dest: /etc/rsyslog.d/99-haproxy.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rsyslog

- name: Create Certificate Folder
  ansible.builtin.file:
    path: "{{ haproxy_cert_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0644
  when: haproxy_cert_name | length > 0

- name: Copy Certificate to Host
  ansible.builtin.copy:
    src: "{{ haproxy_cert_name }}"
    dest: "{{ haproxy_cert_dir }}/{{ haproxy_cert_name }}"
    owner: root
    group: root
    mode: 0644
  when: haproxy_cert_name | length > 0

- name: Create Whitelist Folder
  ansible.builtin.file:
    path: "{{ haproxy_whitelist_file_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0644
  when: haproxy_whitelist_file_name | length > 0

- name: Copy Whitelist File to Host
  ansible.builtin.copy:
    src: "{{ haproxy_whitelist_file_name }}"
    dest: "{{ haproxy_whitelist_file_dir }}/{{ haproxy_whitelist_file_name }}"
    owner: root
    group: root
    mode: 0644
  when: haproxy_whitelist_file_name | length > 0

- name: Ensure log file for HAProxy exists
  ansible.builtin.file:
    path: "{{ haproxy_log_file }}"
    state: touch
    modification_time: "preserve"
    access_time: "preserve"
    owner: root
    group: root
    mode: 0600

- name: Correct logrotate configuration
  ansible.builtin.lineinfile:
    path: "{{ haproxy_logrotate_file }}"
    insertbefore: BOF
    line: "{{ haproxy_log_file }}"

- name: Configure haproxy using haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_destination_config_path }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - validate haproxy config
    - reload haproxy
