---
# handlers file for role_haproxy

- name: reload haproxy
  ansible.builtin.service:
    name: "haproxy"
    state: reloaded

- name: restart rsyslog
  ansible.builtin.service:
    name: "rsyslog"
    state: restarted
