---
# handlers file for role_haproxy

- name: validate haproxy config
  ansible.builtin.command:
    cmd: haproxy -c -f {{ haproxy_destination_config_path }}
  changed_when: false

- name: reload haproxy
  ansible.builtin.service:
    name: "haproxy"
    state: reloaded

- name: restart rsyslog
  ansible.builtin.service:
    name: "rsyslog"
    state: restarted
